version: "2"
plugins:
  bundler-audit:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      # below check are disabled because Codeclimate's Markdownlint is not latest version
      MD023:
        enabled: false
