version: "2"
plugins:
  bundler-audit:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013: # MD013/Line length
        enabled: false
      MD033: # MD033/no-inline-html
        enabled: false
      # below 3 checks are disabled because Codeclimate's Markdownlint is not latest version (0.5.0)
      MD023:
        enabled: false
      MD034:
        enabled: false
      MD036:
        enabled: false
    exclude_patterns:
    - ".chglog/*.tpl.md"
