AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 75
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false
