inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 75
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*
