version: '3.7'

services:
  app:
    depends_on:
      - mysql55
    entrypoint: ./wait-for-mysql.sh mysql55

  mysql55:
    image: mysql:5.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
