version: '3.7'

services:
  app:
    build:
      context: .
      target: ci
    stdin_open: true
    volumes:
      - .:/app
    tmpfs:
      - /app/tmp
      - /app/vendor
    depends_on:
      - db
