version: '3.7'

services:
  mysqldb:
    image: mariadb:5.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
