version: '3.7'

services:
  app:
    build: .
    stdin_open: true
    volumes:
      - .:/app
    tmpfs:
      - /app/tmp
      - /app/vendor
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
