version: '3.7'

services:
  app:
    depends_on:
      - mariadb104
    entrypoint: ./wait-for-mysql.sh mariadb104

  mariadb104:
    image: mariadb:10.4
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
