version: '3.7'

services:
  app:
    depends_on:
      - mariadb100
    entrypoint: ./wait-for-mysql.sh mariadb100

  mariadb100:
    image: mariadb:10.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
