version: '3.7'

services:
  app:
    depends_on:
      - mariadb102
    entrypoint: ./wait-for-mysql.sh mariadb102

  mariadb102:
    image: mariadb:10.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
