version: '3.7'

services:
  db:
    image: mysql:8.0
    # fix for: ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
