version: '3.7'

services:
  app:
    build:
      context: .
      target: docker-compose
    stdin_open: true
    volumes:
      - .:/app
    tmpfs:
      - /app/tmp
      - /app/vendor
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
