version: 2.1

jobs:
  test-ruby27:
    docker:
      - image: ruby:2.7-rc-alpine
    steps:
      - checkout
      - run: apk add git # workaround for alpine..
      - run: ruby -v # debug
      - run: gem install bundler -v 1.17.3
      - run: bundle install -j "$(nproc)"
      - run: bundle exec rspec

workflows:
  test-ruby27:
    jobs:
      - test-ruby27
