version: 2.1

test_attributes: &test_attributes
  docker:
    - image: circleci/buildpack-deps:trusty
  resource_class: small
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build docker image
        command: docker build -t masking-$RUBY_VERSION-$CIRCLE_SHA1 --build-arg ruby_version=$RUBY_VERSION .
    - run:
        name: output Ruby version (debug)
        command: docker run --entrypoint sh masking-$RUBY_VERSION-$CIRCLE_SHA1 -c "ruby -v" # debug
    - run:
        name: run test
        command: docker run --entrypoint sh -e CI -e CODECOV_TOKEN masking-$RUBY_VERSION-$CIRCLE_SHA1 -c "bundle exec rspec"

jobs:
  test-ruby31:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '3.1'
  test-ruby30:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '3.0'
  test-ruby27:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '2.7'
  test-ruby26:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '2.6'
  test-ruby25:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '2.5'

workflows:
  'CircleCI: build':
    jobs:
      - test-ruby26
      - test-ruby25
      - test-ruby27
      - test-ruby30
      - test-ruby31
