version: 2.1

test_steps: &test_steps
  steps:
    - checkout
    - run: docker build -t masking-$CIRCLE_BRANCH-$RUBY_VERSION --build-arg ruby_version=$RUBY_VERSION .
    - run: docker run --entrypoint sh masking-$CIRCLE_BRANCH-$RUBY_VERSION -c "ruby -v" # debug
    - run: docker run --entrypoint sh masking-$CIRCLE_BRANCH-$RUBY_VERSION -c "bundle exec rspec"

jobs:
  test-rubyrc:
    <<: *test_steps
    environment:
      RUBY_VERSION: rc
  test-ruby26:
    <<: *test_steps
    environment:
      RUBY_VERSION: 2.6
  test-ruby25:
    <<: *test_steps
    environment:
      RUBY_VERSION: 2.5

workflows:
  test:
    jobs:
      - test-ruby26
      - test-ruby25
      - test-rubyrc
