version: 2.1

test_attributes: &test_attributes
  machine: true
  steps:
    - checkout
    - run: docker build -t masking-$RUBY_VERSION-$CIRCLE_SHA1 --build-arg ruby_version=$RUBY_VERSION .
    - run: docker run --entrypoint sh masking-$RUBY_VERSION-$CIRCLE_SHA1 -c "ruby -v" # debug
    - run: docker run --entrypoint sh -e CI -e COVERALLS_REPO_TOKEN masking-$RUBY_VERSION-$CIRCLE_SHA1 -c "bundle exec rspec"

jobs:
  test-rubyrc:
    <<: *test_attributes
    environment:
      RUBY_VERSION: rc
  test-ruby26:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '2.6'
  test-ruby25:
    <<: *test_attributes
    environment:
      RUBY_VERSION: '2.5'

workflows:
  'ci/circleci: build':
    jobs:
      - test-ruby26
      - test-ruby25
      - test-rubyrc
