version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb103
    entrypoint: docker-compose/wait-for-mysql.sh mariadb103

  mariadb103:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
