version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb110
    entrypoint: docker-compose/wait-for-mysql.sh mariadb110
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb110:
    image: mariadb:11.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
