version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb104
    entrypoint: docker-compose/wait-for-mysql.sh mariadb104
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb104:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
