version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb1010
    entrypoint: docker-compose/wait-for-mysql.sh mariadb1010

  mariadb1010:
    image: mariadb:10.10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
