version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb1011
    entrypoint: docker-compose/wait-for-mysql.sh mariadb1011

  mariadb1011:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
