version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb106
    entrypoint: docker-compose/wait-for-mysql.sh mariadb106
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb106:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
