version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb104
    entrypoint: docker-compose/wait-for-mysql.sh mariadb107

  mariadb107:
    image: mariadb:10.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
