version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb107
    entrypoint: docker-compose/wait-for-mysql.sh mariadb107
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb107:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
