version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb100
    entrypoint: docker-compose/wait-for-mysql.sh mariadb100
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb100:
    image: mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
