version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb103
    entrypoint: docker-compose/wait-for-mysql.sh mariadb103

  mariadb103:
    image: mariadb:10.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
