version: '3.7'

services:
  app:
    depends_on:
      - mariadb55
    entrypoint: docker-compose/wait-for-mysql.sh mariadb55

  mariadb55:
    image: mariadb:5.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
