version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb105
    entrypoint: docker-compose/wait-for-mysql.sh mariadb105

  mariadb105:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
