version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb55
    entrypoint: docker-compose/wait-for-mysql.sh mariadb55

  mariadb55:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
