version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb55
    entrypoint: docker-compose/wait-for-mysql.sh mariadb55
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb55:
    image: mariadb:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
