version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb102
    entrypoint: docker-compose/wait-for-mysql.sh mariadb102
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb102:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
