version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb109
    entrypoint: docker-compose/wait-for-mysql.sh mariadb109

  mariadb109:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
