version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mariadb112
    entrypoint: docker-compose/wait-for-mysql.sh mariadb112
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb112:
    image: mariadb:11.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
