version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mysql81
    entrypoint: docker-compose/wait-for-mysql.sh mysql81
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql81:
    image: mysql:8.1
    # fix for: ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded:
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
