version: '3.7'

services:
  app:
    depends_on:
      - mysql56
    entrypoint: docker-compose/wait-for-mysql.sh mysql56

  mysql56:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
