version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mysql56
    entrypoint: docker-compose/wait-for-mysql.sh mysql56
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql56:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
