version: '3.7'

services:
  app:
    depends_on:
      - mysql80
    entrypoint: docker-compose/wait-for-mysql.sh mysql80

  mysql80:
    image: mysql:8.0
    # fix for: ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
