version: '3.7'

services:
  app:
    build:
      target: with-mysql-client
    depends_on:
      - mysql57
    entrypoint: docker-compose/wait-for-mysql.sh mysql57
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
