name: Acceptance Test
on: [push, pull_request]

jobs:
  mysql80:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose/mysql80.yml build
      - name: run test
        run: docker-compose/acceptance_test.sh mysql80
  mysql57:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose/mysql57.yml build
      - name: run test
        run: docker-compose/acceptance_test.sh mysql57
