name: Acceptance Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mysql80:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
      - name: run test
        run: docker-compose/acceptance_test.sh mysql80
  mysql57:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
      - name: run test
        run: docker-compose/acceptance_test.sh mysql57
