name: Acceptance Test MariaDB
on:
  push:
    branches:
      - main
  pull_request:

mariadb_attributes: &mariadb_attributes
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1 # shallow clone
    - name: run test
      run: docker-compose/acceptance_test.sh $MARIADB_VERSION docker-compose-ci.yml

jobs:
  mariadb1011:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb1011'
  mariadb1010:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb1010'
  mariadb109:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb109'
  mariadb108:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb108'
  mariadb107:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb107'
  mariadb106:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb106'
  mariadb105:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb105'
  mariadb104:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb104'
  mariadb103:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb103'
  mariadb102:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb102'
  mariadb101:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb101'
  mariadb100:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb100'
  mariadb55:
    <<: *mariadb_attributes
    env:
      MARIADB_VERSION: 'mariadb55'
