name: Acceptance Test
on: [push, pull_request]

jobs:
  mysql80:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
      MYSQL_HOST: mysql80
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose_mysql80.yml build
      - name: run test
        run: docker-compose -f docker-compose.yml -f docker-compose_mysql80.yml run -e MYSQL_HOST=$MYSQL_HOST --entrypoint sh app ./wait-for-mysql.sh $MYSQL_HOST acceptance/run_test.sh
  mysql57:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: mysql57
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose_mysql57.yml build
      - name: run test
        run: docker-compose -f docker-compose.yml -f docker-compose_mysql57.yml run -e MYSQL_HOST=$MYSQL_HOST --entrypoint sh app ./wait-for-mysql.sh $MYSQL_HOST acceptance/run_test.sh
