name: Acceptance Test MySQL
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mysql81:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql81 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mysql80:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql80 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mysql57:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql57 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
