name: Acceptance Test
on: [push, pull_request]

jobs:
  mysql80:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.ci.yml -f docker-compose_mysql80.yml build
      - name: run test
        run: docker-compose -f docker-compose.ci.yml -f docker-compose_mysql80.yml run --entrypoint sh app ./wait-for-mysql.sh db acceptance/run_test.sh
  mysql57:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Build the stack
        run: docker-compose -f docker-compose.ci.yml -f docker-compose_mysql57.yml build
      - name: run test
        run: docker-compose -f docker-compose.ci.yml -f docker-compose_mysql57.yml run --entrypoint sh app ./wait-for-mysql.sh db acceptance/run_test.sh
