name: Acceptance Test MariaDB
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mariadb111:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb111 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb110:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb110 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb1011:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb1011 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb1010:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb1010 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb109:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb109 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb108:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb108 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb107:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb107 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb106:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb106 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb105:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb105 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb104:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb104 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb103:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb103 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
  mariadb102:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb102 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
          DUMPFILE_DEBUG: ${{ vars.DUMPFILE_DEBUG }}
