name: Acceptance Test MySQL
on:
  push:
    branches:
      - main
  pull_request:

jobs:    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql80:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql80 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql57:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql57 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql56 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mysql55:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mysql55 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
