name: Acceptance Test MariaDB
on:
  push:
    branches:
      - main
  pull_request:

env:
  DEBUG: ${{ vars.DEBUG }}

jobs:    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb1011:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb1011 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb1010:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb1010 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb109:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb109 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb108:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb108 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb107:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb107 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb106:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb106 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb105:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb105 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb104:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb104 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb103:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb103 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb102:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb102 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb101:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb101 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb100:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb100 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  mariadb55:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb55 docker-compose-ci.yml
        env:
          TRACE: ${{ vars.TRACE }}
