name: Acceptance Test MariaDB
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mariadb104:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb104
  mariadb103:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb103
  mariadb102:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb102
  mariadb101:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb101
  mariadb100:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb100
  mariadb55:
    runs-on: ubuntu-latest
    env:
      CONTAINER_USER: root
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: docker-compose/acceptance_test.sh mariadb55
