name: Ruby edges
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ruby27:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: run test
        run: bundle exec rspec
        uses: docker://ruby:2.7-rc
